development: &dev
  secret_key_base: 685159eb4b05cba6f8dbf9e75d1f46e2
  telegram:
    bot:
      token: 1262628648:AAHF21l7hwRH-X67-34RKEip2IDwD8dm-Zo
      username: surveilance_kalsel_bot
      # async: true
      # botan:
      #   token: botan_token
      #   # async: true

test:
  secret_key_base: blabla
  telegram:
    bot:
      token: test_bot_token
      username: BOT_NAME

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *dev
