development: &dev
  secret_key_base: 685159eb4b05cba6f8dbf9e75d1f46e2
  telegram:
    bot:
      token: 1223439832:AAHtzvmYmdXG-ZqsuXJZ9Ig_4qsTBTnK2fk
      username: covid19_kalsel_bot
      # async: true
      # botan:
      #   token: botan_token
      #   # async: true

test:
  secret_key_base: blabla
  telegram:
    bot:
      token: test_bot_token
      username: BOT_NAME

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *dev
